### ISSUE TITLE
Nodeset no textures showing up

### ISSUE THREAD

**Issue by phil-kt** [varkenvarken/blenderaddons#8]
I'm trying to import some textures from Substance Painter using this script but none of the textures show up in the file explorer.

<img width="1548" alt="screen shot 2017-10-24 at 12 56 28 am" src="https://user-images.githubusercontent.com/620506/31925354-39f2f9aa-b856-11e7-9f26-2f5db0fdfbcd.png">

![screen shot 2017-10-24 at 12 56 42 am](https://user-images.githubusercontent.com/620506/31925363-435bd994-b856-11e7-8354-877bac2d23a8.png)

Any tips?

**Comment by varkenvarken** [comment]
Could be the .jpeg extension i think the addon only looks for jpg (so without the e)?

**Comment by phil-kt** [comment]
@varkenvarken nah I tried that, and in the Python code it says this:

```
    extensions = StringProperty(
        name="File Extensions Support",
        default='png, jpeg, targa, tiff, exr, hdr',
        description="Comma separated list of extensions for file search")
```

So I don't know why they don't show.

**Comment by varkenvarken** [comment]
Will have a look at it as soon as i can (prob. this weekend). I think it might be in the naming convention: you seem to use albedo for your basic color so you could try to configure the add-on preferences 'basecolor' attribute to look for the pattern 'albedo' in the filename (because the default is to look for 'color')

**Comment by phil-kt** [comment]
It's cool, I ended up just importing each texture as I needed. Thanks!
